debug = false

logLevel = "ERROR"

defaultEntryPoints = ["http", "https"]

[api]
dashboard = true
entrypoint = "reserva"

[entrypoints]

[entrypoints.reserva]
  address = ":8080"
  [entrypoints.reserva.auth]
  [entrypoints.reserva.auth.basic]
        users = ["admin:$apr1$7c6bFgfk$sfgiNCZIgBCizWL5beOWo/"]
    [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
  entryPoint = "https"
    [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

        minVersion = "VersionTLS12"
        cipherSuites = [
          "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
          "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
          "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        ]
        [[entryPoints.https.tls.certificates]]
          certFile = "certs/traefik.crt"
          keyFile = "certs/traefik.key"


[acme]
email = "djamilson@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
main = "ofertadodia.palmas.br"
sub = "ofertadodia.palmas.br"
